# Generated by Django 3.1.7 on 2021-06-21 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('start_price', models.IntegerField()),
                ('now_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 6, 24, 7, 24, 4, 491449, tzinfo=utc))),
                ('remaining_time', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.category')),
            ],
        ),
    ]
